server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hxyttel/SpringCloud.git
          search-paths: config
          username: hxytte;
          password: 0827@1998hxy
        label: master
eureka:
  client:
    service-url:
       defaultZone : http://localhost:8761/eureka/
